# Generated by Django 4.2.4 on 2024-02-11 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='name (what you want this event to be called in the admin interface)')),
                ('title', models.TextField()),
                ('desc', models.TextField(verbose_name='description')),
                ('img', models.ImageField(upload_to='events/', verbose_name='image')),
            ],
        ),
    ]
